name: CI

on:
  push:
    branches:
      - dev
      - release
      - "feature/**"

jobs:
  preinstall:
    name: Pre-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pre-install
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          wget -nd -np -P /tmp https://www.tbi.univie.ac.at/RNA/download/sourcecode/2_4_x/$VIENNARNA.tar.gz
          tar -xf /tmp/$VIENNARNA.tar.gz -C /tmp
          cd /tmp/$VIENNARNA
          ./configure && make -j$(nproc) && make install
        env:
          VIENNARNA: ViennaRNA-2.4.18

  verify:
    name: Verify
    runs-on: ubuntu-latest
    needs: preinstall
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          cargo test --release -q
          cargo package -q
      - name: Benchmark
        run: |
          cargo bench -q

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    needs: preinstall
    steps:
      - uses: actions/checkout@v3
      - name: Check format
        run: |
          rustup component add rustfmt
          cargo fmt --check
      - name: Lint
        run: |
          rustup component add clippy
          cargo clippy -q
